I'm sorry, but an uncaught exception occurred.

While loading <'Image' u'Cloud3(2).png'>:
  File "game/script.rpy", line 304, in script
    Cloud "Well, I HATE women."
IOError: Couldn't find file 'Cloud3(2).png'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 304, in script
    Cloud "Well, I HATE women."
  File "C:\Users\chris\Downloads\renpy-7.4.5-sdk/renpy/ast.py", line 715, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "C:\Users\chris\Downloads\renpy-7.4.5-sdk/renpy/exports.py", line 1417, in say
    who(what, *args, **kwargs)
  File "C:\Users\chris\Downloads\renpy-7.4.5-sdk/renpy/character.py", line 1219, in __call__
    self.do_display(who, what, cb_args=self.cb_args, dtt=dtt, **display_args)
  File "C:\Users\chris\Downloads\renpy-7.4.5-sdk/renpy/character.py", line 871, in do_display
    **display_args)
  File "C:\Users\chris\Downloads\renpy-7.4.5-sdk/renpy/character.py", line 621, in display_say
    rv = renpy.ui.interact(mouse='say', type=type, roll_forward=roll_forward)
  File "C:\Users\chris\Downloads\renpy-7.4.5-sdk/renpy/ui.py", line 298, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "C:\Users\chris\Downloads\renpy-7.4.5-sdk/renpy/display/core.py", line 3213, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, **kwargs)
  File "C:\Users\chris\Downloads\renpy-7.4.5-sdk/renpy/display/core.py", line 3729, in interact_core
    self.draw_screen(root_widget, fullscreen_video, (not fullscreen_video) or video_frame_drawn)
  File "C:\Users\chris\Downloads\renpy-7.4.5-sdk/renpy/display/core.py", line 2466, in draw_screen
    renpy.config.screen_height,
  File "render.pyx", line 492, in renpy.display.render.render_screen
  File "render.pyx", line 263, in renpy.display.render.render
  File "C:\Users\chris\Downloads\renpy-7.4.5-sdk/renpy/display/layout.py", line 783, in render
    surf = render(child, width, height, cst, cat)
  File "render.pyx", line 170, in renpy.display.render.render
  File "render.pyx", line 263, in renpy.display.render.render
  File "C:\Users\chris\Downloads\renpy-7.4.5-sdk/renpy/display/transition.py", line 368, in render
    top = render(self.new_widget, width, height, st, at)
  File "render.pyx", line 170, in renpy.display.render.render
  File "render.pyx", line 263, in renpy.display.render.render
  File "C:\Users\chris\Downloads\renpy-7.4.5-sdk/renpy/display/layout.py", line 783, in render
    surf = render(child, width, height, cst, cat)
  File "render.pyx", line 170, in renpy.display.render.render
  File "render.pyx", line 263, in renpy.display.render.render
  File "C:\Users\chris\Downloads\renpy-7.4.5-sdk/renpy/display/layout.py", line 783, in render
    surf = render(child, width, height, cst, cat)
  File "render.pyx", line 170, in renpy.display.render.render
  File "render.pyx", line 263, in renpy.display.render.render
  File "C:\Users\chris\Downloads\renpy-7.4.5-sdk/renpy/display/transform.py", line 706, in render
    return transform_render(self, width, height, st, at)
  File "accelerator.pyx", line 140, in renpy.display.accelerator.transform_render
  File "render.pyx", line 263, in renpy.display.render.render
  File "C:\Users\chris\Downloads\renpy-7.4.5-sdk/renpy/display/image.py", line 501, in render
    return wrap_render(self.target, width, height, st, at)
  File "C:\Users\chris\Downloads\renpy-7.4.5-sdk/renpy/display/image.py", line 307, in wrap_render
    rend = render(child, w, h, st, at)
  File "render.pyx", line 170, in renpy.display.render.render
  File "render.pyx", line 263, in renpy.display.render.render
  File "C:\Users\chris\Downloads\renpy-7.4.5-sdk/renpy/display/im.py", line 607, in render
    return cache.get(self, render=True)
  File "C:\Users\chris\Downloads\renpy-7.4.5-sdk/renpy/display/im.py", line 271, in get
    surf = image.load()
  File "C:\Users\chris\Downloads\renpy-7.4.5-sdk/renpy/display/im.py", line 688, in load
    raise e
IOError: Couldn't find file 'Cloud3(2).png'.

Windows-10-10.0.19041
Ren'Py 7.4.5.1648
The Average Day in L'stanberg 1.0
Sat Jun 19 18:30:34 2021
