I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 203, in script
    python:
  File "renpy/common/00start.rpy", line 278, in <module>
    renpy.call_in_new_context("_main_menu")
JumpException: LOL, GET FUCKED! Man, i used to be such a big fan of you dream. Why are you so scared to call out your fans. Stop hiding behid 'Its only a small perrcentage of my community. Fuck off. Choose a new name.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 203, in script
    python:
  File "renpy/ast.py", line 922, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "renpy/python.py", line 2218, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "renpy/common/00start.rpy", line 278, in <module>
    renpy.call_in_new_context("_main_menu")
  File "renpy/game.py", line 349, in call_in_new_context
    raise renpy.game.JumpException(e.args[0])
JumpException: LOL, GET FUCKED! Man, i used to be such a big fan of you dream. Why are you so scared to call out your fans. Stop hiding behid 'Its only a small perrcentage of my community. Fuck off. Choose a new name.

Windows-10-10.0.19041
Ren'Py 7.4.5.1648
The Average Day in L'stanberg 1.0
Sun Jun 20 19:16:42 2021
